feat: add error checking for dependency path

diff --git a/action.yaml b/action.yaml
--- a/action.yaml
+++ b/action.yaml
@@ -26,7 +26,14 @@ runs:
 
     - name: Install dependencies
       shell: bash
-      run: python -m pip install -r ${{ github.action_path }}/requirements.txt
+      run: |
+        echo "Installing dependencies from action's requirements.txt"
+        if [[ ! -f "${{ github.action_path }}/requirements.txt" ]]; then
+          echo "::error::Requirements file not found at ${{ github.action_path }}/requirements.txt"
+          exit 1
+        fi
+
+        python -m pip install -r ${{ github.action_path }}/requirements.txt
 
     - name: Validate galaxy.yml
       shell: bash
